<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Magento\Sales\Block\Adminhtml\Order\AbstractOrder
 */
/** @var \Magento\Shipping\Helper\Data $shippingHelper */
$shippingHelper = $block->getData('shippingHelper');
/** @var \Magento\Tax\Helper\Data $taxHelper */
$taxHelper = $block->getData('taxHelper');
?>
<?php $order = $block->getOrder() ?>

<?php if ($order->getShippingDeliveryDate()):
    $date = $order->getShippingDeliveryDate();
    $formattedDate = date('d M Y', strtotime($date));
    ?>
    <strong>
        <?= $escaper->escapeHtml(__('Expected delivery date : '.$formattedDate)); ?>
    </strong>
<?php endif; ?>