<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php $_order = $block->getOrder() ?>

<?php if ($_order->getShippingDeliveryDate()): ?>
    <label class="exptected-delivery">
        <?= $escaper->escapeHtml(
            __('Expected delivery date : %1', date('d M Y', strtotime($_order->getShippingDeliveryDate())))
        ); ?>
    </label>
<?php endif; ?>
